name: "Suspicious Netlify Hosted link"
description: "This rule detects messages containing links to a netlify.app hosted page. This is commonly observed in both Malware and Credential Phishing campaigns. "
references: 
  - "https://rules.emergingthreats.net/open/suricata-5.0/rules/emerging-hunting.rules"
type: "rule"
severity: "medium"
source: |
name: "Suspicious Netlify Hosted link (unsolicited)"
description: "This rule detects messages containing links to a netlify.app hosted page. This is commonly observed in both Malware and Credential Phishing campaigns. "
references: 
  - "https://rules.emergingthreats.net/open/suricata-5.0/rules/emerging-hunting.rules"
type: "rule"
severity: "medium"
source: |
  type.inbound
  and any(body.links,
          regex.imatch(.href_url.domain.domain,
                       '[a-z0-9]+\-[a-z0-9]+\-[a-f0-9]{6}\.netlify\.app'
          )
  )
  and (
    not profile.by_sender().solicited
    or profile.by_sender().any_messages_malicious_or_spam
  )
  and not profile.by_sender().any_false_positives
  
  // negate highly trusted sender domains unless they fail DMARC authentication
  and (
    (
      sender.email.domain.root_domain in $high_trust_sender_root_domains
      and (
        any(distinct(headers.hops, .authentication_results.dmarc is not null),
            strings.ilike(.authentication_results.dmarc, "*fail")
        )
      )
    )
    or sender.email.domain.root_domain not in $high_trust_sender_root_domains
  )
tags:
 - "Attack surface reduction"
attack_types:
  - "Credential Phishing"
  - "Malware/Ransomware"
detection_methods:
  - "URL analysis"


tags:
 - "Attack surface reduction"
attack_types:
  - "Credential Phishing"
  - "Malware/Ransomware"
detection_methods:
  - "URL analysis"

id: "2364afa8-177d-56f2-947e-107439e0cca0"
