name: "Suspicious Netlify Hosted link"
description: "This rule detects messages containing links to a netlify.app hosted page. This is commonly observed in both Malware and Credential Phishing campaigns. "
references: 
  - "https://rules.emergingthreats.net/open/suricata-5.0/rules/emerging-hunting.rules"
type: "rule"
severity: "medium"
source: |
  type.inbound
  and any(body.links,
          regex.imatch(.href_url.domain.domain,
                       '[a-z0-9]+\-[a-z0-9]+\-[a-f0-9]{6}\.netlify\.app'
          )
  )
tags:
 - "Attack surface reduction"
attack_types:
  - "Credential Phishing"
  - "Malware/Ransomware"
detection_methods:
  - "URL analysis"

