name: 'Mark stale pull requests'
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 14
          stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent activity for 14 days.'
          stale-pr-label: 'stale'
          days-before-close: -1  # Set to -1 to disable closing
          remove-stale-when-updated: true
          exempt-issue-labels: '*'
          exempt-pr-labels: ''
          only-issue-labels: ''
          only-pr-labels: ''
          ascending: false
          debug-only: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
